---
title: The N Days Of Christmas
hero_image: images/banner.png
description: In this resource you will create a script that will print out the song
  The N Days of Christmas song
original_url: https://raspberrypi.org/learning/n-days-of-christmas
theme: red
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: What next?

