title: The N Days of Christmas
hero_image: images/banner.png
description: Create a script that will print out the song 'The N Days of Christmas'
original_url: https://raspberrypi.org/learning/n-days-of-christmas
theme: red
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: The N Days Of Christmas
- title: Getting the text files
- title: Importing the words
- title: Getting all the verbs and nouns
- title: Getting some random nouns
- title: Pairing verbs and nouns
- title: Turning loops to list comprehensions
- title: Getting suffixes for numerals
- title: Printing the whole song
- title: What next?
